# SITE CONFIGURATION
baseurl: "/SHD-India"
url: "http://sciencehackday.in"
title: SHD India # site's title
description: "Science Hack Day India 2018" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: SHD India # blog's title
  avatar: assets/img/shdsmalllogo.png
  favicon: assets/img/shdsmalllogo.png
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p><h1>Science Hack Day India - 2018</h1><strong> 2 - 4  November 2018</strong> <br> <h3>Let's collaborate, learn, hack, build cool stuff with science and have lots of fun... </h3></p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "https://www.facebook.com/sciencehackin/"
  flickr: "https://www.flickr.com/groups/3087939@N23/pool/"
  gitlab:
  github: "ScienceHackDayIndia"
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "@SHD_India" # "twitter username"
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: true
    tumblr:
    pinterest:
    pocket:
    reddit:
    linkedin:
    wordpress:
    email:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: #"search"
      enabled: #true
    tags:
      icon: #"tags"
      enabled: #true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 3
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
